"""empty message

Revision ID: 703fb1e81799
Revises: 873e98068ece
Create Date: 2023-12-03 21:59:32.298894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703fb1e81799'
down_revision = '873e98068ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
